### PR TITLE
Feat/haystack integration

### PR DESCRIPTION
**Pull request by bergr7**
__Summary__
Create haystack integration and new tutorial.

__Description__
- Haystack integration
- Fix `_determine_batch_size` in `FlowJudgeHFModel`
- Haystack tutorial

This has been tested locally.

There are no automated tests for integrations yet. Waiting for unit tests revamp.

### CODE REVIEW

**Comment by sariola** [comment]
note to add dependency

image

**Comment by bergr7** [comment]
> note to add dependency
> 
> 
> 
> image

It's in a comment at the top of the notebook. Same as it llama index tutorial.

Do you think we need to add it as a dependency to our pyproject.toml?

**Comment by sariola** [comment]
> > note to add dependency
> > image
> 
> It's in a comment at the top of the notebook. Same as in llama index tutorial.
> 
> Do you think we need to add it as a dependency to our pyproject.toml?

I understand.

How about something of this sort? There are always people who don't read like me.

```
try:
    from haystack import Document
except ImportError:
    print("Haystack is not installed. ")
    print("Please install it according to the 'Additional Requirements' section above.")
    print("\nAfter installation, restart the kernel and run this cell again.")
```

**Comment by bergr7** [comment]
> > > note to add dependency
> > > image
> > 
> > 
> > It's in a comment at the top of the notebook. Same as in llama index tutorial.
> > Do you think we need to add it as a dependency to our pyproject.toml?
> 
> I understand.
> 
> How about something of this sort? There are always people who don't read like me.
> 
> ```
> try:
>     from haystack import Document
> except ImportError:
>     print("Haystack is not installed. ")
>     print("Please install it according to the 'Additional Requirements' section above.")
>     print("\nAfter installation, restart the kernel and run this cell again.")
>     raise SystemExit("Stopping execution due to missing Haystack dependency.")
> ```

Added suggestion to llama index and haystack tutorials.

**Comment by sariola** [comment]
Could add that for a finegrained token need to enable these permission scopes
image

**Comment by sariola** [comment]
The batch eval at the end takes about 2 min per run and uses multi-gpu ok via accelerate. Works :ok: 
image

**Comment by sariola** [comment]
I consider it E2E tested from my side!

**Comment by sariola** [comment]
Note: Doesn't seem to handle parse errors gracefully.

image

**Comment by bergr7** [comment]
> The batch eval at the end takes about 2 min per run and uses multi-gpu ok via accelerate. Works 🆗 image

yes it's quite slow... hopefully we can replace with vllm engine soon or cpu.

**Comment by bergr7** [comment]
> Does it handle parsing errors for you guys?
> 
> image

flow-judge does, haystack doesn't. I don't know if there is a way of working around them. Need to check.

**Comment by sariola** [comment]
> > Does it handle parsing errors for you guys?
> > image
> 
> I guess this is due to the phi-3 issue? have you checked the output?

Yeah, I'm on it. I think the onnxruntime engine just takes up all the VRAM and cranks even on the sync exec. I'm making some changes to the current test implementation of batch_generate of the class. Should be done in a bit.

**Pull request merged**
